### PR TITLE
Add windows auto discovery, more LCD feedback and optional wifi settings reset button.

### PR DESCRIPTION
**Pull request by errolt**
Hi toxuin,

I have made a few additions that might be useful. As I said elsewhere, I'm new to arduino + ESP so the code might not be optimal.

I have added a printer name to the initial setup page, for in case you have multiple ESP boards on one network.

I have added the SSDP service which is windows' equivalent of apple's mdns, the printer now shows up in windows' network neighborhood, double clicking it goes to the ESP's web page.

I have added an optional button for the clearing of wifi settings. On the Nodemcu this is GPIO 16.

I have added more feedback on the printer LCD as to the connection to the wifi network etc.

I have not connected this to a printer yet, though.

Thank you,
Errol

### CODE REVIEW

**Comment by errolt** [comment]
I have also moved the printing of the IP on the LCD from the connect function to right after successful wifi connection.

**Comment by toxuin** [comment]
Looks good!
"Printer name", however, is probably not the best term here since RepRapFirmware already defines a machine name that is then handed over to web interface as a printer name. Adding such config var could bring confusion. Since this only affects the hostname in mDNS and SSDP it would be wiser to name it as hostname or, maybe, moduleName.
Apart from that it's all good.

**Comment by errolt** [comment]
Will update quickly.

**Comment by errolt** [comment]
Yep, should be 96. :) Changed to 32+64 for clarity.

hostname is already defined in lwip stack, it seems. Had to user webhostname. Is this acceptable?

**Comment by toxuin** [comment]
Sounds fine!

**Pull request merged**
